language: java
before_install:
  - npm install -g bower
  - bower install
install: true
before_script: "mvn --settings ./.travis.maven-settings.xml clean"
script: "mvn --settings ./.travis.maven-settings.xml test"
